//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WineListKO
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Color { get; set; }
        public int TermExposure { get; set; }
        public int Fortress { get; set; }
        public decimal Price { get; set; }
    }
}
